# Lab 3: Exploratory Data Analysis and Data Quality Assessment Using Python

### Data Quality Checks
1. How many rows and columns are in the dataset?
2. What are the data types of each column?
3. Are there any missing values?
4. Are there duplicate records?

### Employee Overview
5. How many employees are there in the dataset?
6. How many departments exist in the organization?
7. What are the departments present in the dataset?
8. What is the minimum and maximum employee age?
9. What is the average monthly income?
10. What is the gender distribution of employees?
11. How many employees belong to each department?
12. How many employees have more than 10 years of experience?
13. How many employees have been with the company for more than 5 years?

### Department Analysis
14. What is the average monthly income for each department?
15. How many employees left the company in each department?

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('hr_analytics.csv')
df

,Age,Attrition,Department,Gender,MonthlyIncome,TotalWorkingYears,YearsAtCompany
0,20,No,Research & Development,Female,2116,22,0
1,38,No,Research & Development,Female,12195,28,0
2,37,No,Research & Development,Male,15426,26,3
3,29,No,Research & Development,Male,11916,4,4
4,23,No,Sales,Female,8911,29,8
...,...,...,...,...,...,...,...
299,28,No,Research & Development,Female,4131,22,11
300,37,No,Sales,Female,12128,33,2
301,49,No,Sales,Male,6332,29,0
302,21,No,Sales,Male,5903,3,3
303,59,No,Research & Development,Male,2478,30,1

In [3]:
df.shape

(304, 7)

In [4]:
print(df.dtypes)

Age                  int64
Attrition              str
Department             str
Gender                 str
MonthlyIncome        int64
TotalWorkingYears    int64
YearsAtCompany       int64
dtype: object

In [5]:
df.isnull()

,Age,Attrition,Department,Gender,MonthlyIncome,TotalWorkingYears,YearsAtCompany
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
299,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False
303,False,False,False,False,False,False,False

In [6]:
df.isnull().sum()

Age                  0
Attrition            0
Department           0
Gender               0
MonthlyIncome        0
TotalWorkingYears    0
YearsAtCompany       0
dtype: int64

In [7]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
299    False
300     True
301     True
302     True
303     True
Length: 304, dtype: bool

In [8]:
print(df.duplicated().sum())

4

In [9]:
len(df)

304

In [10]:
df['Department'].nunique()

3

In [11]:
df['Department'].unique()

<StringArray>
['Research & Development', 'Sales', 'Human Resources']
Length: 3, dtype: str

In [12]:
print("Min Age:", df['Age'].min())
print("Max Age:", df['Age'].max())

Min Age: 18
Max Age: 60

In [13]:
print(round(df['MonthlyIncome'].mean(), 2))

10910.78

In [14]:
df['Gender'].value_counts()

Gender
Male      158
Female    146
Name: count, dtype: int64

In [15]:
df['Department'].value_counts()

Department
Research & Development    192
Sales                     100
Human Resources            12
Name: count, dtype: int64

In [16]:
t = df['TotalWorkingYears'] > 10
print(t.sum())

212

In [17]:
c = df['YearsAtCompany'] > 5
print(c.sum())

165

In [18]:
dept_salary = df.groupby('Department')['MonthlyIncome'].mean()
dept_salary

Department
Human Resources           11561.666667
Research & Development    10712.052083
Sales                     11214.220000
Name: MonthlyIncome, dtype: float64

In [19]:
df.groupby('Department')['Attrition'].count()

Department
Human Resources            12
Research & Development    192
Sales                     100
Name: Attrition, dtype: int64